#!/usr/bin/env bash

cmd="$(brew list --formula --installed-on-request -1 | sed "s/.*/'&',/")"

if [[ ! -z "$WAYLAND_DISPLAY" ]] && command -v wl-copy &> /dev/null; then
  printf '%s' "$cmd" | wl-copy
elif [[ ! -z "$DISPLAY" ]] && command -v xclip &> /dev/null; then
  printf '%s' "$cmd" | xclip -selection clipboard
elif [[ ! -z "$DISPLAY" ]] && command -v xsel &> /dev/null; then
  printf '%s' "$cmd" | xsel --clipboard
fi
