#!/usr/bin/env bash

cmd="$(dnf repoquery --userinstalled --qf "'%{name}',\n")"

if [[ ! -z "$WAYLAND_DISPLAY" ]] && command -v wl-copy &> /dev/null; then
  printf '%s' "$cmd" | wl-copy
elif [[ ! -z "$DISPLAY" ]] && command -v xclip &> /dev/null; then
  printf '%s' "$cmd" | xclip -selection clipboard
elif [[ ! -z "$DISPLAY" ]] && command -v xsel &> /dev/null; then
  printf '%s' "$cmd" | xsel --clip
fi
